#!/usr/bin/env node
/*
jails -- farmework script
Copyright (C) 2014 Ivan Popovski

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
var path = require('path');

if(process.argv.length < 3) {
  console.log('Usage: script/jails <command> <argument> <...>');
  process.exit(0);
}

var component = process.argv.slice(2, 4);
var argv = process.argv.slice(4);
var script = path.resolve('./lib', component[0], component[1] || '');

require(script) (argv);
